### PR TITLE
Update to 2.6.2

### PR DESCRIPTION
**Pull request by doompling**
I was looking at our Liquid version and noticed we're on 2.5.0, but 2.6.x still maintains 1.8.7 compatibility. This PR is to update to 2.6.2 which has a fair amount of security/bug fixes compared to 2.5.0.

### CODE REVIEW

**Comment by doompling** [comment]
ping @darkhelmet, not sure if you would have seen a notification otherwise.

**Comment by darkhelmet** [comment]
Looks good to me! We'll have to do some good testing even if all the tests pass.

**Comment by darkhelmet** [comment]
:ship:

**Comment by doompling** [comment]
I don't actually have write access to the liquid, so you'll have to merge this one. I'll make a PR in the measure repo to update the version in our Gemfile once it's been merged though.

**Comment by darkhelmet** [comment]
@pheen Merged!

**Pull request merged**
